### PR TITLE
Forthel examples

### PR DESCRIPTION
**Pull request by McEarl**
* Provide a LaTeX package for ForTheL texts
* Some LaTeX fixes

### CODE REVIEW

**Comment by anfelor** [comment]
Does `stack test` succeed here?

**Comment by adrianmartir** [comment]
The tests succeed.

**Comment by adrianmartir** [comment]
Now this pull request also splits tokens at `_` in tex mode.

**Comment by McEarl** [comment]
Now `stack test` succeeds on my machine, too.

**Pull request merged**
